services:
  postgres:
    image: postgres:16-alpine
    ports:
      - "5436:5432"
    environment:
      POSTGRES_USER: stonetrade
      POSTGRES_PASSWORD: stonetrade
      POSTGRES_DB: stonetrade
    volumes:
      - stonetrade_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U stonetrade"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  stonetrade_data:
